on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:        
        qtversion: [ '5.15.1' ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.9.0
      with: 
        version: ${{ matrix.qtversion }}
        extra: '--archives qt qtbase qtdeclarative qtquickcontrols2 icu tools_qtcreator'
   
    - name: Create Build Environment
      run: ls /home/runner/work/qtorm/Qt/
      #run: qbs-setup-qt --detect
