on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:        
        qtversion: [ '5.15.1' ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.9.0
      with: 
        version: ${{ matrix.qtversion }}
        extra: '--archives qt qtbase qtdeclarative qtquickcontrols2 icu'
   
    - name: Install Qbs
      run: |
        wget --no-check-certificate --content-disposition https://download.qt.io/official_releases/qbs/1.18.0/qbs-linux-x86_64-1.18.0.tar.gz
        tar xzvf qbs-linux-x86_64-1.18.0.tar.gz
        QBS_BIN_DIR="$HOME/usr/local/bin"
        echo ${QBS_BIN_DIR} >> ${GITHUB_PATH}
        echo ${QBS_BIN_DIR}
        ls
        ls ${QBS_BIN_DIR}
        qbs --version
      shell: bash
